proseWrap: always
semi: false
singleQuote: true
printWidth: 80
trailingComma: none
htmlWhitespaceSensitivity: ignore
plugins:
  - prettier-plugin-tailwindcss
  - prettier-plugin-pkgsort
  - '@ianvs/prettier-plugin-sort-imports'

importOrder:
  [
    '',
    '<TYPES>^(node:)',
    '<TYPES>',
    '<TYPES>^[.]',
    '<BUILTIN_MODULES>',
    '<THIRD_PARTY_MODULES>',
    '^[.]',
    '^(?!.*[.]css$)[./].*$',
    '.css$'
  ]
