name = "api"
main = ".output/server/index.mjs"
workers_dev = false
account_id = "02f3b11d8d1017a20f95de4ba88fb5d6"
compatibility_date = "2022-09-10"

routes = [
  { pattern = "api.fmhy.net", custom_domain = true, zone_id = "b4212298934f7c1998b4d15f6d261715" },
]

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "69420"
simple = { limit = 100, period = 60 }
